#!/bin/bash
case "${@: -1}" in
  *forecastedr*)
    sleep 0.3
    if [[ ${@: -1} == *10.2039* ]]; then
      printf '{"type":"FeatureCollection","features":[{"properties":{"rain-precipitation-rate":0.0006,"step":"2026-01-15T13:00:00Z"}},{"properties":{"rain-precipitation-rate":0.0009,"step":"2026-01-15T14:00:00Z"}}]}\n'
    else
      printf '{"type":"FeatureCollection","features":[{"properties":{"rain-precipitation-rate":0,"step":"2026-01-15T13:00:00Z"}},{"properties":{"rain-precipitation-rate":0,"step":"2026-01-15T14:00:00Z"}}]}\n'
    fi
    ;;
  *) printf '{"city":"Odense","latitude":55.4038,"longitude":10.4024}\n' ;;
esac
